<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_blocks',
		'title' => 'Blocks',
		'fields' => array (
			array (
				'key' => 'field_535a9a0c7638b',
				'label' => 'Blocks',
				'name' => 'blocks',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Billboard slider',
						'name' => 'billboard_slider',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_535aa90f48cd6',
								'label' => 'Posts source',
								'name' => 'posts_source',
								'type' => 'select',
								'instructions' => 'Select what type of posts to be displayed.',
								'column_width' => '',
								'choices' => array (
									'featured' => 'Featured posts',
									'latest' => 'Latest posts',
									'latest_by_cat' => 'Latest posts from a category',
									'latest_by_format' => 'Latest posts by post format',
									'latest_by_reviews' => 'Latest posts with reviews',
								),
								'default_value' => 'latest',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_535aa9cf48cd7',
								'label' => 'Category',
								'name' => 'posts_source_category',
								'type' => 'taxonomy',
								'instructions' => 'Hold down Command key (or CTRL on Windows) to select multiple categories.',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'multi_select',
								'allow_null' => 1,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_535ab04da3a7c',
								'label' => 'Post formats',
								'name' => 'posts_source_post_formats',
								'type' => 'select',
								'instructions' => 'Hold down Command key (or CTRL on Windows) to select multiple post formats.',
								'column_width' => '',
								'choices' => array (
									'standard' => 'Standard',
									'gallery' => 'Gallery',
									'video' => 'Video',
									'audio' => 'Audio',
								),
								'default_value' => 'standard',
								'allow_null' => 0,
								'multiple' => 1,
							),
							array (
								'key' => 'field_535ab1bd5ae23',
								'label' => 'Number of posts',
								'name' => 'number_of_posts',
								'type' => 'number',
								'instructions' => 'Set the maximum number of posts to be displayed.',
								'column_width' => '',
								'default_value' => 6,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array (
								'key' => 'field_535ab1e85ae24',
								'label' => 'Read More Label',
								'name' => 'read_more_label',
								'type' => 'text',
								'instructions' => 'Main Slider Read More Link Text',
								'column_width' => '',
								'default_value' => 'Read full story',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_535ab2425ae25',
								'label' => 'Slider transition',
								'name' => 'slider_transition',
								'type' => 'select',
								'instructions' => 'Select the transition between slides.',
								'column_width' => '',
								'choices' => array (
									'fade' => 'Fade',
									'slide' => 'Slide',
								),
								'default_value' => 'slide',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_535ab28e5ae26',
								'label' => 'Slider auto play',
								'name' => 'slider_auto_play',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_535ab2df5ae27',
								'label' => 'Delay between slides on autoplay in miliseconds',
								'name' => 'slider_autoplay_delay',
								'type' => 'number',
								'instructions' => '1000 ms = 1 second',
								'column_width' => '',
								'default_value' => 3000,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 1000,
								'max' => 9000,
								'step' => '',
							),
						),
					),
					array (
						'label' => 'Billboard posts',
						'name' => 'billboard_posts',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_5365133319d96',
								'label' => 'Post source',
								'name' => 'posts_source',
								'type' => 'select',
								'instructions' => 'Select what type of posts to be displayed.',
								'column_width' => '',
								'choices' => array (
									'featured' => 'Featured posts',
									'latest' => 'Latest posts',
									'latest_by_cat' => 'Latest posts from a category',
									'latest_by_format' => 'Latest posts by post format',
									'latest_by_reviews' => 'Latest posts with reviews',
								),
								'default_value' => 'latest',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5365137219d97',
								'label' => 'Category',
								'name' => 'posts_source_category',
								'type' => 'taxonomy',
								'instructions' => 'Hold down Command key (or CTRL on Windows) to select multiple categories.',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'multi_select',
								'allow_null' => 1,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_5365139d19d98',
								'label' => 'Post formats',
								'name' => 'posts_source_post_formats',
								'type' => 'select',
								'instructions' => 'Hold down Command key (or CTRL on Windows) to select multiple post formats.',
								'column_width' => '',
								'choices' => array (
									'standard' => 'Standard',
									'gallery' => 'Gallery',
									'video' => 'Video',
									'audio' => 'Audio',
								),
								'default_value' => 'standard',
								'allow_null' => 0,
								'multiple' => 1,
							),
						),
					),
					array (
						'label' => 'Posts grid',
						'name' => 'posts_grid',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_535b654a88384',
								'label' => 'Posts source',
								'name' => 'posts_source',
								'type' => 'select',
								'instructions' => 'Select what type of posts to be displayed.',
								'column_width' => '',
								'choices' => array (
									'featured' => 'Featured posts',
									'latest' => 'Latest posts',
									'latest_by_cat' => 'Latest posts from a category',
									'latest_by_format' => 'Latest posts by post format',
									'latest_by_reviews' => 'Latest posts with reviews',
								),
								'default_value' => 'latest',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_535b657c88385',
								'label' => 'Category',
								'name' => 'posts_source_category',
								'type' => 'taxonomy',
								'instructions' => 'Hold down Command key (or CTRL on Windows) to select multiple categories.',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'multi_select',
								'allow_null' => 1,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_535b65b088386',
								'label' => 'Post formats',
								'name' => 'posts_source_post_formats',
								'type' => 'select',
								'instructions' => 'Hold down Command key (or CTRL on Windows) to select multiple post formats.',
								'column_width' => '',
								'choices' => array (
									'standard' => 'Standard',
									'gallery' => 'Gallery',
									'video' => 'Video',
									'audio' => 'Audio',
								),
								'default_value' => 'standard',
								'allow_null' => 0,
								'multiple' => 1,
							),
							array (
								'key' => 'field_535b65e688387',
								'label' => 'Number of posts',
								'name' => 'number_of_posts',
								'type' => 'number',
								'instructions' => 'Set the maximum number of posts to be displayed.',
								'column_width' => '',
								'default_value' => 6,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
					),
					array (
						'label' => 'Heading title',
						'name' => 'heading_title',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_535b8553869d3',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Html editor',
						'name' => 'html_editor',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_535bd290fe026',
								'label' => 'Editor',
								'name' => 'editor',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Papa grid',
						'name' => 'papa_grid',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_535c8d5b5449d',
								'label' => 'Posts source',
								'name' => 'posts_source',
								'type' => 'select',
								'instructions' => 'Select what type of posts to be displayed.',
								'column_width' => '',
								'choices' => array (
									'featured' => 'Featured posts',
									'latest' => 'Latest posts',
									'latest_by_cat' => 'Latest posts from a category',
									'latest_by_format' => 'Latest posts by post format',
									'latest_by_reviews' => 'Latest posts with reviews',
								),
								'default_value' => 'latest',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_535c8d7e5449e',
								'label' => 'Category',
								'name' => 'posts_source_category',
								'type' => 'taxonomy',
								'instructions' => 'Hold down Command key (or CTRL on Windows) to select multiple categories.',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'multi_select',
								'allow_null' => 1,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_535c8da05449f',
								'label' => 'Post format',
								'name' => 'posts_source_post_formats',
								'type' => 'select',
								'instructions' => 'Hold down Command key (or CTRL on Windows) to select multiple post formats.',
								'column_width' => '',
								'choices' => array (
									'standard' => 'Standard',
									'gallery' => 'Gallery',
									'video' => 'Video',
									'audio' => 'Audio',
								),
								'default_value' => 'standard',
								'allow_null' => 0,
								'multiple' => 1,
							),
							array (
								'key' => 'field_535c8dd7544a0',
								'label' => 'Number of posts',
								'name' => 'number_of_posts',
								'type' => 'number',
								'instructions' => 'Set the maximum number of posts to be displayed.',
								'column_width' => '',
								'default_value' => 6,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
					),
					array (
						'label' => 'Latest articles',
						'name' => 'latest_articles',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_5360eef4ba7be',
								'label' => 'Number of posts',
								'name' => 'number_of_posts',
								'type' => 'number',
								'column_width' => '',
								'default_value' => 10,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array (
								'key' => 'field_5360ef2cba7bf',
								'label' => 'Layout',
								'name' => 'layout',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'grid' => 'Masonry',
									'list' => 'Classic',
								),
								'default_value' => 'masonry',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5360ef73ba7c0',
								'label' => 'Enable pagination',
								'name' => 'enable_pagination',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 1,
							),
							array (
								'key' => 'field_5360ef9eba7c1',
								'label' => 'Section title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => 'Latest posts',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5360efb9ba7c2',
								'label' => 'Enable sidebar',
								'name' => 'enable_sidebar',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
				),
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/custom-page-builder.php',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_category-options',
		'title' => 'Category options',
		'fields' => array (
			array (
				'key' => 'field_5363bd615239c',
				'label' => 'Category color',
				'name' => 'category_color',
				'type' => 'color_picker',
				'instructions' => 'Choose the main color for this category',
				'default_value' => '',
			),
			array (
				'key' => 'field_5363d1ae23acf',
				'label' => 'Category background color',
				'name' => 'category_background_color',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array (
				'key' => 'field_5363bdc3966d7',
				'label' => 'Background image',
				'name' => 'cat_background_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5363c884fecd4',
				'label' => 'Add container shadow',
				'name' => 'container_shadow',
				'type' => 'select',
				'choices' => array (
					'none' => 'None',
					'light' => 'Light',
					'medium' => 'Medium',
					'dark' => 'Dark',
				),
				'default_value' => 'none',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53739feeaf848',
				'label' => 'Category layout',
				'name' => 'category_layout',
				'type' => 'select',
				'choices' => array (
					'default' => 'Default',
					'grid' => 'Grid',
					'list' => 'List',
				),
				'default_value' => 'default',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'category',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-review',
		'title' => 'Post review',
		'fields' => array (
			array (
				'key' => 'field_535ce72bd6d40',
				'label' => 'Enable post review',
				'name' => 'enable_post_review',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_535ce771d6d41',
				'label' => 'Score breakdown',
				'name' => 'score_breakdown',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_535ce72bd6d40',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_535ce795d6d42',
						'label' => 'Label',
						'name' => 'label',
						'type' => 'text',
						'column_width' => 50,
						'default_value' => '',
						'placeholder' => 'e.g. Design quality',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_535ce7e2d6d43',
						'label' => 'Score',
						'name' => 'score',
						'type' => 'text',
						'column_width' => 50,
						'default_value' => 5,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add new criteria',
			),
			array (
				'key' => 'field_535ceacd6fb2f',
				'label' => 'Score box',
				'name' => 'score_box',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_535ce72bd6d40',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'before' => 'Before content',
					'after' => 'After content',
				),
				'default_value' => 'before',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_535ceb596fb30',
				'label' => 'Score note',
				'name' => 'score_note',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_535ce72bd6d40',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'Add a short note about the score ( optional )',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-parallax-header',
		'title' => 'Post parallax header',
		'fields' => array (
			array (
				'key' => 'field_53751a41156f1',
				'label' => 'Enable parallax header',
				'name' => 'enable_parallax_header',
				'type' => 'true_false',
				'instructions' => 'mark this option if you want to use a parallax image as header',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53751a6e156f2',
				'label' => 'Parallax image',
				'name' => 'parallax_image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53751a41156f1',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_image-source',
		'title' => 'Image source',
		'fields' => array (
			array (
				'key' => 'field_53970a06cdebe',
				'label' => 'Enable image source',
				'name' => 'enable_image_source',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53970a1bcdebf',
				'label' => 'Label',
				'name' => 'image_src_label',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53970a06cdebe',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53970a33cdec0',
				'label' => 'External url',
				'name' => 'image_src_url',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53970a06cdebe',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
}
?>